# Generated by Django 2.2.13 on 2021-08-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderitem_item_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Of', 'Oficina'), ('Cs', 'Casual'), ('Fi', 'Fiesta')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('O', 'Oferta'), ('N', 'Nuevo'), ('U', 'Últimas')], max_length=1),
        ),
    ]
